In [8]:
import pandas as pd
# Load with error handling
df = pd.read_csv("broken-csv.txt", on_bad_lines="skip")

In [9]:
# Fill missing ages with average
df['age'] = df['age'].fillna(df['age'].mean())
df

,id,name,email,signup_date,age
0,1,Ada Lovelace,ada@example.org,2026-01-04,38.000000
1,2,"Linus Torvalds, Jr.",linus@example.com,2026-01-05,54.000000
2,3,Grace Hopper,grace@example.org,2026-01-06,41.000000
3,4,"Margaret ""Hamilton""",margaret@example.com,2026-01-07,32.000000
4,5,Alan Turing,"alan@example.com,backup@example.com",2026-01-08,29.000000
5,6,Edsger Dijkstra,edsger@example.org,not-a-date,57.000000
6,7,"Ken,Thompson",ken@example.com,2026-01-10,42.555556
7,8,Dennis Ritchie,dennis@example.org,2026-01-11,33.000000
8,9,Donald Knuth,donald@example.org,2026-01-12,71.000000
9,10,"Barbara ""Liskov",liskov@example.com,2026-01-13,28.000000

In [10]:
# Convert signup_date to datetime, replace errors with NaT
df['signup_date'] = pd.to_datetime(df['signup_date'], errors='coerce')  
df

,id,name,email,signup_date,age
0,1,Ada Lovelace,ada@example.org,2026-01-04,38.000000
1,2,"Linus Torvalds, Jr.",linus@example.com,2026-01-05,54.000000
2,3,Grace Hopper,grace@example.org,2026-01-06,41.000000
3,4,"Margaret ""Hamilton""",margaret@example.com,2026-01-07,32.000000
4,5,Alan Turing,"alan@example.com,backup@example.com",2026-01-08,29.000000
5,6,Edsger Dijkstra,edsger@example.org,NaT,57.000000
6,7,"Ken,Thompson",ken@example.com,2026-01-10,42.555556
7,8,Dennis Ritchie,dennis@example.org,2026-01-11,33.000000
8,9,Donald Knuth,donald@example.org,2026-01-12,71.000000
9,10,"Barbara ""Liskov",liskov@example.com,2026-01-13,28.000000

In [11]:
# Keep only the first email if multiple are present
df['email'] = df['email'].str.split(',').str[0]
df

   id                 name                 email signup_date        age
0   1         Ada Lovelace       ada@example.org  2026-01-04  38.000000
1   2  Linus Torvalds, Jr.     linus@example.com  2026-01-05  54.000000
2   3         Grace Hopper     grace@example.org  2026-01-06  41.000000
3   4  Margaret "Hamilton"  margaret@example.com  2026-01-07  32.000000
4   5          Alan Turing      alan@example.com  2026-01-08  29.000000
5   6      Edsger Dijkstra    edsger@example.org         NaT  57.000000
6   7         Ken,Thompson       ken@example.com  2026-01-10  42.555556
7   8       Dennis Ritchie    dennis@example.org  2026-01-11  33.000000
8   9         Donald Knuth    donald@example.org  2026-01-12  71.000000
9  10      Barbara "Liskov    liskov@example.com  2026-01-13  28.000000

In [12]:
df.drop_duplicates(inplace=True)
df

   id                 name                 email signup_date        age
0   1         Ada Lovelace       ada@example.org  2026-01-04  38.000000
1   2  Linus Torvalds, Jr.     linus@example.com  2026-01-05  54.000000
2   3         Grace Hopper     grace@example.org  2026-01-06  41.000000
3   4  Margaret "Hamilton"  margaret@example.com  2026-01-07  32.000000
4   5          Alan Turing      alan@example.com  2026-01-08  29.000000
5   6      Edsger Dijkstra    edsger@example.org         NaT  57.000000
6   7         Ken,Thompson       ken@example.com  2026-01-10  42.555556
7   8       Dennis Ritchie    dennis@example.org  2026-01-11  33.000000
8   9         Donald Knuth    donald@example.org  2026-01-12  71.000000
9  10      Barbara "Liskov    liskov@example.com  2026-01-13  28.000000

In [13]:
df['name'] = df['name'].str.replace('"','')
df

   id                 name                 email signup_date        age
0   1         Ada Lovelace       ada@example.org  2026-01-04  38.000000
1   2  Linus Torvalds, Jr.     linus@example.com  2026-01-05  54.000000
2   3         Grace Hopper     grace@example.org  2026-01-06  41.000000
3   4    Margaret Hamilton  margaret@example.com  2026-01-07  32.000000
4   5          Alan Turing      alan@example.com  2026-01-08  29.000000
5   6      Edsger Dijkstra    edsger@example.org         NaT  57.000000
6   7         Ken,Thompson       ken@example.com  2026-01-10  42.555556
7   8       Dennis Ritchie    dennis@example.org  2026-01-11  33.000000
8   9         Donald Knuth    donald@example.org  2026-01-12  71.000000
9  10       Barbara Liskov    liskov@example.com  2026-01-13  28.000000

In [14]:
df['domain'] = df['email'].str.split('@').str[1]
df

,id,name,email,signup_date,age,domain
0,1,Ada Lovelace,ada@example.org,2026-01-04,38.000000,example.org
1,2,"Linus Torvalds, Jr.",linus@example.com,2026-01-05,54.000000,example.com
2,3,Grace Hopper,grace@example.org,2026-01-06,41.000000,example.org
3,4,Margaret Hamilton,margaret@example.com,2026-01-07,32.000000,example.com
4,5,Alan Turing,alan@example.com,2026-01-08,29.000000,example.com
5,6,Edsger Dijkstra,edsger@example.org,NaT,57.000000,example.org
6,7,"Ken,Thompson",ken@example.com,2026-01-10,42.555556,example.com
7,8,Dennis Ritchie,dennis@example.org,2026-01-11,33.000000,example.org
8,9,Donald Knuth,donald@example.org,2026-01-12,71.000000,example.org
9,10,Barbara Liskov,liskov@example.com,2026-01-13,28.000000,example.com

In [15]:
df['year'] = df['signup_date'].dt.year
df

,id,name,email,signup_date,age,domain,year
0,1,Ada Lovelace,ada@example.org,2026-01-04,38.000000,example.org,2026.0
1,2,"Linus Torvalds, Jr.",linus@example.com,2026-01-05,54.000000,example.com,2026.0
2,3,Grace Hopper,grace@example.org,2026-01-06,41.000000,example.org,2026.0
3,4,Margaret Hamilton,margaret@example.com,2026-01-07,32.000000,example.com,2026.0
4,5,Alan Turing,alan@example.com,2026-01-08,29.000000,example.com,2026.0
5,6,Edsger Dijkstra,edsger@example.org,NaT,57.000000,example.org,NaN
6,7,"Ken,Thompson",ken@example.com,2026-01-10,42.555556,example.com,2026.0
7,8,Dennis Ritchie,dennis@example.org,2026-01-11,33.000000,example.org,2026.0
8,9,Donald Knuth,donald@example.org,2026-01-12,71.000000,example.org,2026.0
9,10,Barbara Liskov,liskov@example.com,2026-01-13,28.000000,example.com,2026.0