In [1]:
import pandas as pd
# Load with error handling
df = pd.read_csv("broken-csv.txt", on_bad_lines="skip")

In [2]:
# Use signup_date as index
df.set_index('signup_date', inplace=True)

# Reset back to default
df.reset_index(inplace=True)
df

,signup_date,id,name,email,age
0,2026-01-04,1,Ada Lovelace,ada@example.org,38.0
1,2026-01-05,2,"Linus Torvalds, Jr.",linus@example.com,54.0
2,2026-01-06,3,Grace Hopper,grace@example.org,41.0
3,2026-01-07,4,"Margaret ""Hamilton""",margaret@example.com,32.0
4,2026-01-08,5,Alan Turing,"alan@example.com,backup@example.com",29.0
5,not-a-date,6,Edsger Dijkstra,edsger@example.org,57.0
6,2026-01-10,7,"Ken,Thompson",ken@example.com,NaN
7,2026-01-11,8,Dennis Ritchie,dennis@example.org,33.0
8,2026-01-12,9,Donald Knuth,donald@example.org,71.0
9,2026-01-13,10,"Barbara ""Liskov",liskov@example.com,28.0

In [3]:
# Extract domain from email
df['domain'] = df['email'].map(lambda x: x.split('@')[1])
df

,signup_date,id,name,email,age,domain
0,2026-01-04,1,Ada Lovelace,ada@example.org,38.0,example.org
1,2026-01-05,2,"Linus Torvalds, Jr.",linus@example.com,54.0,example.com
2,2026-01-06,3,Grace Hopper,grace@example.org,41.0,example.org
3,2026-01-07,4,"Margaret ""Hamilton""",margaret@example.com,32.0,example.com
4,2026-01-08,5,Alan Turing,"alan@example.com,backup@example.com",29.0,"example.com,backup"
5,not-a-date,6,Edsger Dijkstra,edsger@example.org,57.0,example.org
6,2026-01-10,7,"Ken,Thompson",ken@example.com,NaN,example.com
7,2026-01-11,8,Dennis Ritchie,dennis@example.org,33.0,example.org
8,2026-01-12,9,Donald Knuth,donald@example.org,71.0,example.org
9,2026-01-13,10,"Barbara ""Liskov",liskov@example.com,28.0,example.com

In [4]:
# Convert wide format to long format
melted = pd.melt(df, id_vars=['id','name'], value_vars=['age','domain'])
print(melted.head())

   id                 name variable value
0   1         Ada Lovelace      age  38.0
1   2  Linus Torvalds, Jr.      age  54.0
2   3         Grace Hopper      age  41.0
3   4  Margaret "Hamilton"      age  32.0
4   5          Alan Turing      age  29.0

In [5]:
# Pivot table of age by domain
pivot = df.pivot_table(values='age', index='domain', aggfunc='mean')
print(pivot)

                     age
domain
example.com         38.0
example.com,backup  29.0
example.org         48.0